<a href="https://colab.research.google.com/github/lakshitgosain/Tensorflow-ZTM/blob/main/00_TF_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#In this NB, we are going to cover some of the most fundamental concepts of tensorflow

More specifically, we are going to cover
- Intro to tensors
- Getting information from tensors
- Manipulating tensors
- Tensors and Numpy
using @tf.functions (a way to speed up your regular python functions)
- using GPS


#Introduction to Tensors

In [1]:
#import tensorflow
import tensorflow as tf

In [ ]:
print(tf.__version__)

2.11.0


In [ ]:
#Creating tensors with tf.constant()
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#Check the number of dimensions of a tensor
scalar.ndim

0

In [ ]:
#Create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
#Create a matrix
matrix=tf.constant([[10,7],
                   [7,10]])

In [ ]:
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
#The number of elements in shape is the ndim

In [ ]:
another_matrix=tf.constant([[10.,7.],
                            [7.,10.],
                            [8.,9.]],dtype=tf.float16)#specify the datatype with dtype parameter

In [ ]:
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
#Create a tensor
tensor=tf.constant([[[1,2,3],
                     [4,5,6]],
                    [[7,8,9],
                     [10,11,12]],
                    [[13,14,15],
                     [16,17,18]]])

In [ ]:
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

What we've created so far
- scalar - a single number
- Vector- a number with Direction (e.g. wind speed and direction)
- Matrix- a 2-Dimension array of numbers
- Tensor - A n-dimensional array of numbers, where n can be any number . 

Creating Tensors using tf.variable() 

In [5]:
#Create the same variable with tf.variable as above
changable_tensor=tf.Variable([10,7])

In [3]:
unchangable_tensor=tf.constant([10,7])

In [7]:
changable_tensor,unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [8]:
#What if we try to change one of the elements in out changable tensor?
changable_tensor[0]=7

TypeError: ignored

In [9]:
#How about we try .assign
changable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [10]:
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [12]:
#How about we change a value in Unchangable tensor
unchangable_tensor[0]=7

TypeError: ignored

In [13]:
unchangable_tensor[0].assign(7)

AttributeError: ignored

NOTE: Rarely you would be in a situation to decide between tf.tensor and tf.variable. If in doubt, use tf.variable

##Creating Random Tensors

- Tensors of some arbitary size with Random Values

In [18]:
random_1=tf.random.Generator.from_seed(42) #using Seed for reproducability
random_1=random_1.normal(shape=(3,2))

In [19]:
random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))

In [20]:
random_1, random_2, random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

##shuffle the order of elements in a tensor
If the dataset is in order, it could affect how our Neural Network could learn. It would have random examples to learn from

In [2]:
#Shuffle a tensor (Valuable for when you want to shuffle your data so that the inherent order doesn't affect learning)

not_shuffled=tf.constant([[10,7],
                          [3,4],
                          [2,5]])

In [3]:
not_shuffled.ndim

2

In [4]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [6]:
#Shuffle our non-shuffled tensor
shuffled=tf.random.shuffle(not_shuffled)

In [7]:
shuffled #It has shuffled it along it's first dimension.

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [8]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [10]:
#Shuffle our non-shuffled tensor

shuffled=tf.random.shuffle(not_shuffled,seed=42) #We still get different results. THis is because we are using a operation level seed and not a global level seed
shuffled

In [15]:
tf.random.set_seed(42) #Global level random seed

shuffled=tf.random.shuffle(not_shuffled,seed=42) #Operation Level seed
shuffled
#We get the same order everytime if we are using both global and operation level seed.\
#It looks like if we want out shuffled tensors to be in the same order every time, we've got to use both global and operational level seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

## Other ways to make tensors

In [16]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [17]:
tf.zeros([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

## Turn numpy Arrays into tensors
the main difference b/w np and tensorflow is that tensors can run on a GPU computing fater

In [21]:
# You can also turn np arrays into tensorflow tensors
import numpy as np
numpy_A= np.arange(1,25,dtype=np.int32)
numpy_A
# X=tf.constant(some matrix) #Capital for matrix or tensor
# y=tf.constant(vector) #non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [22]:
A=tf.constant(numpy_A,shape=(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [26]:
B=tf.constant(numpy_A)
B

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [25]:
#if wwe ant to convert the shape of the tensor, the elements in the new shape should be matching up with the elements in the old tensor.

###Getting information from tensors
When dealing with tensors, we would be need to aware of the followiung attributes
* shape
* Rank
* Axis/Dimension
* Size


In [28]:
A.ndim

3

In [29]:
#Create a rank 4 tensor(4 dimensions)

rank_4_tensor=tf.zeros(shape=(2,3,4,5))

In [30]:
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [31]:
rank_4_tensor.ndim

4

In [32]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [35]:
tf.size(rank_4_tensor) #2*3*4*5=120

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [39]:
#Get various attributes of our tensors
print("Datatype of every element: ", rank_4_tensor.dtype)
print("shape of the tensor: ", rank_4_tensor.shape)
print("No. of dimensions(rank): ", rank_4_tensor.ndim)
print("Elements along with 0 axis: ",rank_4_tensor.shape[0])
print("Elements along with last axis: ",rank_4_tensor.shape[-1])
print("Total number of elements in our tensor: ",tf.size(rank_4_tensor))
print("Total number of elements in our tensor: ",tf.size(rank_4_tensor).numpy()) #To get the single element

Datatype of every element:  <dtype: 'float32'>
shape of the tensor:  (2, 3, 4, 5)
No. of dimensions(rank):  4
Elements along with 0 axis:  2
Elements along with last axis:  5
Total number of elements in our tensor:  tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor:  120


##Indexing and expanding the tensors

Tensors can be indexed just like a Python list


In [40]:
#Get the first 2 elements of each dimension of the rank_4_tensor

In [41]:
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [43]:
#Get the first element  dimension from each index except from the final one
rank_4_tensor[:1,:1,:1]
#same as 
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [44]:
rank_4_tensor[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [45]:
rank_4_tensor[:,:1,:1,:1]

<tf.Tensor: shape=(2, 1, 1, 1), dtype=float32, numpy=
array([[[[0.]]],


       [[[0.]]]], dtype=float32)>

In [46]:
#Changing or adding an extra dimension at the end of the tensor
#create a rank 2 tensor
rank_2_tensor=tf.constant([[10,7],
                          [3,4]])

In [47]:
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [48]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [50]:
#get the last item of each row of our rank 2 tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [51]:
#add an extra dimension to our rank 2 tensor

rank_3_tensor=rank_2_tensor[...,tf.newaxis] #... to add axis at the very end

In [52]:
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [53]:
#Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor,axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [55]:
tf.expand_dims(rank_2_tensor,axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

## Manipulating tensors(Tensor Operations)

### Basic Operations


In [58]:
#You can add values to a tensor using addition operator
tensor=tf.constant([[10,7],[3,4]])
tensor+10 #Original Tensor is unchanged

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [59]:
#Multiplication also works
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [60]:
#Subtraction
tensor-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [62]:
#We can also use equialent tensorflow builtin functions
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [63]:
tf.add(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [64]:
tf.subtract(tensor,10
            )

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [65]:
tensor #The tensor's value is still not changed

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

**Matrix Multiplication**

In machine learning, Matrix multiplication is one of the most common operation

There are 2 rules that our tensors and matrices need to fulfill
* The inner dimensions need to match
* The resulting matrix has the shape of outer dimensions

In [66]:
#matrix Multiplicatio in tensorflow
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [67]:
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [70]:
#Matrix Multiplication with python operator '@'
tensor@tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [71]:
tensor.shape

TensorShape([2, 2])