<a href="https://colab.research.google.com/github/lakshitgosain/Tensorflow-ZTM/blob/main/00_TF_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#In this NB, we are going to cover some of the most fundamental concepts of tensorflow

More specifically, we are going to cover
- Intro to tensors
- Getting information from tensors
- Manipulating tensors
- Tensors and Numpy
using @tf.functions (a way to speed up your regular python functions)
- using GPS


#Introduction to Tensors

In [1]:
#import tensorflow
import tensorflow as tf

In [2]:
print(tf.__version__)

2.11.0


In [3]:
#Creating tensors with tf.constant()
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
#Check the number of dimensions of a tensor
scalar.ndim

0

In [6]:
#Create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
vector.ndim

1

In [10]:
#Create a matrix
matrix=tf.constant([[10,7],
                   [7,10]])

In [11]:
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [12]:
matrix.ndim

2

In [13]:
#The number of elements in shape is the ndim

In [14]:
another_matrix=tf.constant([[10.,7.],
                            [7.,10.],
                            [8.,9.]],dtype=tf.float16)#specify the datatype with dtype parameter

In [15]:
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 8.,  9.]], dtype=float16)>

In [16]:
another_matrix.ndim

2

In [18]:
#Create a tensor
tensor=tf.constant([[[1,2,3],
                     [4,5,6]],
                    [[7,8,9],
                     [10,11,12]],
                    [[13,14,15],
                     [16,17,18]]])

In [19]:
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [21]:
tensor.ndim

3

What we've created so far
- scalar - a single number
- Vector- a number with Direction (e.g. wind speed and direction)
- Matrix- a 2-Dimension array of numbers
- Tensor - A n-dimensional array of numbers, where n can be any number . 