<a href="https://colab.research.google.com/github/lakshitgosain/Tensorflow-ZTM/blob/main/00_TF_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#In this NB, we are going to cover some of the most fundamental concepts of tensorflow

More specifically, we are going to cover
- Intro to tensors
- Getting information from tensors
- Manipulating tensors
- Tensors and Numpy
using @tf.functions (a way to speed up your regular python functions)
- using GPS


#Introduction to Tensors

In [3]:
#import tensorflow
import tensorflow as tf

In [ ]:
print(tf.__version__)

2.11.0


In [20]:
#Creating tensors with tf.constant()
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#Check the number of dimensions of a tensor
scalar.ndim

0

In [ ]:
#Create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
#Create a matrix
matrix=tf.constant([[10,7],
                   [7,10]])

In [ ]:
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
#The number of elements in shape is the ndim

In [ ]:
another_matrix=tf.constant([[10.,7.],
                            [7.,10.],
                            [8.,9.]],dtype=tf.float16)#specify the datatype with dtype parameter

In [ ]:
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
#Create a tensor
tensor=tf.constant([[[1,2,3],
                     [4,5,6]],
                    [[7,8,9],
                     [10,11,12]],
                    [[13,14,15],
                     [16,17,18]]])

In [ ]:
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

What we've created so far
- scalar - a single number
- Vector- a number with Direction (e.g. wind speed and direction)
- Matrix- a 2-Dimension array of numbers
- Tensor - A n-dimensional array of numbers, where n can be any number . 

Creating Tensors using tf.variable() 

In [5]:
#Create the same variable with tf.variable as above
changable_tensor=tf.Variable([10,7])

In [3]:
unchangable_tensor=tf.constant([10,7])

In [7]:
changable_tensor,unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [8]:
#What if we try to change one of the elements in out changable tensor?
changable_tensor[0]=7

TypeError: ignored

In [9]:
#How about we try .assign
changable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [10]:
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [12]:
#How about we change a value in Unchangable tensor
unchangable_tensor[0]=7

TypeError: ignored

In [13]:
unchangable_tensor[0].assign(7)

AttributeError: ignored

NOTE: Rarely you would be in a situation to decide between tf.tensor and tf.variable. If in doubt, use tf.variable

##Creating Random Tensors

- Tensors of some arbitary size with Random Values

In [18]:
random_1=tf.random.Generator.from_seed(42) #using Seed for reproducability
random_1=random_1.normal(shape=(3,2))

In [19]:
random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))

In [20]:
random_1, random_2, random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

##shuffle the order of elements in a tensor
If the dataset is in order, it could affect how our Neural Network could learn. It would have random examples to learn from

In [2]:
#Shuffle a tensor (Valuable for when you want to shuffle your data so that the inherent order doesn't affect learning)

not_shuffled=tf.constant([[10,7],
                          [3,4],
                          [2,5]])

In [3]:
not_shuffled.ndim

2

In [4]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [6]:
#Shuffle our non-shuffled tensor
shuffled=tf.random.shuffle(not_shuffled)

In [7]:
shuffled #It has shuffled it along it's first dimension.

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [8]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [10]:
#Shuffle our non-shuffled tensor

shuffled=tf.random.shuffle(not_shuffled,seed=42) #We still get different results. THis is because we are using a operation level seed and not a global level seed
shuffled

In [21]:
tf.random.set_seed(42) #Global level random seed

shuffled=tf.random.shuffle(not_shuffled,seed=42) #Operation Level seed
shuffled
#We get the same order everytime if we are using both global and operation level seed.\
#It looks like if we want out shuffled tensors to be in the same order every time, we've got to use both global and operational level seed

TypeError: ignored

## Other ways to make tensors

In [16]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [17]:
tf.zeros([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

## Turn numpy Arrays into tensors
the main difference b/w np and tensorflow is that tensors can run on a GPU computing fater

In [21]:
# You can also turn np arrays into tensorflow tensors
import numpy as np
numpy_A= np.arange(1,25,dtype=np.int32)
numpy_A
# X=tf.constant(some matrix) #Capital for matrix or tensor
# y=tf.constant(vector) #non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [22]:
A=tf.constant(numpy_A,shape=(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [26]:
B=tf.constant(numpy_A)
B

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [25]:
#if wwe ant to convert the shape of the tensor, the elements in the new shape should be matching up with the elements in the old tensor.

###Getting information from tensors
When dealing with tensors, we would be need to aware of the followiung attributes
* shape
* Rank
* Axis/Dimension
* Size


In [28]:
A.ndim

3

In [29]:
#Create a rank 4 tensor(4 dimensions)

rank_4_tensor=tf.zeros(shape=(2,3,4,5))

In [30]:
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [31]:
rank_4_tensor.ndim

4

In [32]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [35]:
tf.size(rank_4_tensor) #2*3*4*5=120

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [39]:
#Get various attributes of our tensors
print("Datatype of every element: ", rank_4_tensor.dtype)
print("shape of the tensor: ", rank_4_tensor.shape)
print("No. of dimensions(rank): ", rank_4_tensor.ndim)
print("Elements along with 0 axis: ",rank_4_tensor.shape[0])
print("Elements along with last axis: ",rank_4_tensor.shape[-1])
print("Total number of elements in our tensor: ",tf.size(rank_4_tensor))
print("Total number of elements in our tensor: ",tf.size(rank_4_tensor).numpy()) #To get the single element

Datatype of every element:  <dtype: 'float32'>
shape of the tensor:  (2, 3, 4, 5)
No. of dimensions(rank):  4
Elements along with 0 axis:  2
Elements along with last axis:  5
Total number of elements in our tensor:  tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor:  120


##Indexing and expanding the tensors

Tensors can be indexed just like a Python list


In [40]:
#Get the first 2 elements of each dimension of the rank_4_tensor

In [41]:
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [43]:
#Get the first element  dimension from each index except from the final one
rank_4_tensor[:1,:1,:1]
#same as 
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [44]:
rank_4_tensor[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [45]:
rank_4_tensor[:,:1,:1,:1]

<tf.Tensor: shape=(2, 1, 1, 1), dtype=float32, numpy=
array([[[[0.]]],


       [[[0.]]]], dtype=float32)>

In [46]:
#Changing or adding an extra dimension at the end of the tensor
#create a rank 2 tensor
rank_2_tensor=tf.constant([[10,7],
                          [3,4]])

In [47]:
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [48]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [50]:
#get the last item of each row of our rank 2 tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [51]:
#add an extra dimension to our rank 2 tensor

rank_3_tensor=rank_2_tensor[...,tf.newaxis] #... to add axis at the very end

In [52]:
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [53]:
#Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor,axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [55]:
tf.expand_dims(rank_2_tensor,axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

## Manipulating tensors(Tensor Operations)

### Basic Operations


In [58]:
#You can add values to a tensor using addition operator
tensor=tf.constant([[10,7],[3,4]])
tensor+10 #Original Tensor is unchanged

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [59]:
#Multiplication also works
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [60]:
#Subtraction
tensor-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [62]:
#We can also use equialent tensorflow builtin functions
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [63]:
tf.add(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [64]:
tf.subtract(tensor,10
            )

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [65]:
tensor #The tensor's value is still not changed

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

**Matrix Multiplication**

In machine learning, Matrix multiplication is one of the most common operation

There are 2 rules that our tensors and matrices need to fulfill
* The inner dimensions need to match
* The resulting matrix has the shape of outer dimensions

In [66]:
#matrix Multiplicatio in tensorflow
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [67]:
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [70]:
#Matrix Multiplication with python operator '@'
tensor@tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [71]:
tensor.shape

TensorShape([2, 2])

In [73]:
#We can reshape the tensors
tf.reshape(rank_3_tensor,shape=(1,2,2))

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [75]:
# Can we do transpose
tf.transpose(tensor)

#Transpose switches the axises while reshape flips the tensor to the shape we want

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  3],
       [ 7,  4]], dtype=int32)>

**The dot Product**
Matrix multiplication is also reffered to as dot product

* tf.matmul()
* tf.tensordot()

In [80]:
#preform the dot product on X and Y using tensordot
X=tf.constant([[1,2],
              [3,4],
              [5,6]])
Y=tf.constant([[7,8],
               [9,10],
               [11,12]])

tf.tensordot(X,tf.transpose(Y),axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [83]:
tf.tensordot(tf.transpose(X),Y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [84]:
tf.matmul(X,tf.reshape(Y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [87]:
#We get different results from transpose and reshape
#Check the values of Y,reshaped Y and transposed Y

print(Y)
print("Reshaped Y: ", tf.reshape(Y, shape=(2,3)))
print("Transposed Y: ", tf.transpose(Y))

tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)
Reshaped Y:  tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)
Transposed Y:  tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


## Changing the Datatype of the tensors

In [88]:
#Create a new tensor with default datatype

B=tf.constant([1.7,7.4])

In [90]:
B.dtype

tf.float32

In [94]:
#Change from float 32 to float16( This is called reduced precision- helps in faster compute/training/processing)
B=tf.cast(B, dtype=tf.float16)

In [95]:
B.dtype

tf.float16

## Tensor Aggregation

Aggregation = Condensing them from multiple values down to a smaller amount of values

In [98]:
#Getting the absolute values
D=tf.constant([-7,-10])
D
tf.abs(D) #Take the negative numbers and turn them into positive

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

### Let's go through the following forms of aggregation:
* Get the minimum
* get the maximum
* Get the mean of the Tensor
* Ge the sum of a tensor

In [6]:
#Create a Random tensor with random values b/w 0-100 of size 50
E=tf.constant(np.random.randint(0,100,size=(50)))

NameError: ignored

In [100]:
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 0, 48, 71, 28, 41, 96, 23,  5, 38, 35, 58, 54, 17, 14, 30, 50, 73,
       72, 53, 21, 43,  9, 68, 87, 73, 86, 98, 27, 91, 11, 77, 38, 93, 71,
        9, 21, 93, 93, 87, 80, 14,  1, 44, 40, 50, 32, 99, 64, 79, 61])>

In [101]:
tf.size(E),E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [102]:
#Find the Minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [103]:
#Find the max
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [104]:
#Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=51>

In [105]:
#Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2566>

In [107]:
#Find the variance
#tfp# Tensorflow probability
import tensorflow_probability as tfp

In [108]:
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=880>

In [111]:
tf.math.reduce_std(tf.cast(E,tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=29.678572>

In [5]:
#Find the variance
tf.math.reduce_variance(tf.cast(E,dtype=tf.float32))

NameError: ignored

## Find the positional max and Minimum in the tensor

Useful when the represenation outputs are a prediction Probability. We would be able to deduce which one has the highest value. 
At which index of the tensor does the maximum value occur

In [3]:
#Create a new tensor for finding positional min and max
tf.random.set_seed(42)
F=tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [6]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [7]:
#Index on our largest value
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [8]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [9]:
#check for equality
assert F[tf.argmax(F)] == tf.reduce_max(F)

In [10]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [11]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Squezing a Tensor (Removing all single dimensions)

In [16]:
tf.random.set_seed(42)
G=tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))

In [17]:
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [18]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [19]:
G_squezzed=tf.squeeze(G)

In [21]:
G_squezzed, G_squezzed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

### One-Hot Encode tensors

In [26]:
some_list= [0,1,2,3]
#One hot encode our list of indices

tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [27]:
#Specify custom values for one-hot encoding
tf.one_hot(some_list, depth=4, on_value="Hellp", off_value= 'I love Dance')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Hellp', b'I love Dance', b'I love Dance', b'I love Dance'],
       [b'I love Dance', b'Hellp', b'I love Dance', b'I love Dance'],
       [b'I love Dance', b'I love Dance', b'Hellp', b'I love Dance'],
       [b'I love Dance', b'I love Dance', b'I love Dance', b'Hellp']],
      dtype=object)>

## Trying more Math Functions
Squaring, Log, Sqrt

In [8]:
H=tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [9]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [10]:
tf.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [13]:
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

## Tensorflow and Numpy

Tensorflow interacts beautifully with Numpy Arrays

In [15]:
import numpy as np

In [16]:
#Create a tensor directly from numpy arraty
J=tf.constant(np.array([3.,7.,10.]))

In [18]:
#Convert the tensor back to Numpy Array
np.array(J),type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [20]:
#Convert the tensor J to numpy
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [24]:
#The Default types of each are slightly different

numpy_J=tf.constant(np.array([3.,7.,10.]))
tensor_J=tf.constant([3.,7.,10.])

#Check the types of both
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)