<a href="https://colab.research.google.com/github/lakshitgosain/Tensorflow-ZTM/blob/main/00_TF_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#In this NB, we are going to cover some of the most fundamental concepts of tensorflow

More specifically, we are going to cover
- Intro to tensors
- Getting information from tensors
- Manipulating tensors
- Tensors and Numpy
using @tf.functions (a way to speed up your regular python functions)
- using GPS


#Introduction to Tensors

In [2]:
#import tensorflow
import tensorflow as tf

In [ ]:
print(tf.__version__)

2.11.0


In [ ]:
#Creating tensors with tf.constant()
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#Check the number of dimensions of a tensor
scalar.ndim

0

In [ ]:
#Create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
#Create a matrix
matrix=tf.constant([[10,7],
                   [7,10]])

In [ ]:
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
#The number of elements in shape is the ndim

In [ ]:
another_matrix=tf.constant([[10.,7.],
                            [7.,10.],
                            [8.,9.]],dtype=tf.float16)#specify the datatype with dtype parameter

In [ ]:
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
#Create a tensor
tensor=tf.constant([[[1,2,3],
                     [4,5,6]],
                    [[7,8,9],
                     [10,11,12]],
                    [[13,14,15],
                     [16,17,18]]])

In [ ]:
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

What we've created so far
- scalar - a single number
- Vector- a number with Direction (e.g. wind speed and direction)
- Matrix- a 2-Dimension array of numbers
- Tensor - A n-dimensional array of numbers, where n can be any number . 

Creating Tensors using tf.variable() 

In [5]:
#Create the same variable with tf.variable as above
changable_tensor=tf.Variable([10,7])

In [3]:
unchangable_tensor=tf.constant([10,7])

In [7]:
changable_tensor,unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [8]:
#What if we try to change one of the elements in out changable tensor?
changable_tensor[0]=7

TypeError: ignored

In [9]:
#How about we try .assign
changable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [10]:
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [12]:
#How about we change a value in Unchangable tensor
unchangable_tensor[0]=7

TypeError: ignored

In [13]:
unchangable_tensor[0].assign(7)

AttributeError: ignored

NOTE: Rarely you would be in a situation to decide between tf.tensor and tf.variable. If in doubt, use tf.variable

##Creating Random Tensors

- Tensors of some arbitary size with Random Values

In [18]:
random_1=tf.random.Generator.from_seed(42) #using Seed for reproducability
random_1=random_1.normal(shape=(3,2))

In [19]:
random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))

In [20]:
random_1, random_2, random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)