<a href="https://colab.research.google.com/github/lakshitgosain/Tensorflow-ZTM/blob/main/TF_ZTM_07_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NLP Fundamentals in TF

Sequence-to-sequence
* One to one- Image Captioning
* Many to one- Sentiment analysis
* Many to one- time series forecasting
* many- to-many- Machine translation


In [90]:
!nvidia-smi -L

/bin/bash: nvidia-smi: command not found


In [91]:
!wget https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/extras/helper_functions.py

--2023-06-16 03:12:50--  https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/extras/helper_functions.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.110.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10246 (10K) [text/plain]
Saving to: ‘helper_functions.py.1’

helper_functions.py 100%[===================>]  10.01K  --.-KB/s    in 0s      

2023-06-16 03:12:50 (66.8 MB/s) - ‘helper_functions.py.1’ saved [10246/10246]



In [92]:
from helper_functions import unzip_data, create_tensorboard_callback, plot_loss_curves, compare_historys

In [93]:
!wget "https://storage.googleapis.com/ztm_tf_course/nlp_getting_started.zip"

--2023-06-16 03:12:50--  https://storage.googleapis.com/ztm_tf_course/nlp_getting_started.zip
Resolving storage.googleapis.com (storage.googleapis.com)... 142.251.107.128, 74.125.196.128, 74.125.134.128, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.251.107.128|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 607343 (593K) [application/zip]
Saving to: ‘nlp_getting_started.zip.1’

nlp_getting_started 100%[===================>] 593.11K  --.-KB/s    in 0.006s  

2023-06-16 03:12:51 (102 MB/s) - ‘nlp_getting_started.zip.1’ saved [607343/607343]



In [94]:
unzip_data("nlp_getting_started.zip")

## Visualize the dataset

To visualize the sample data, we need to read the in. On way is to use python.

Another way to do this is use pandas



In [95]:
import pandas as pd
train_df=pd.read_csv("train.csv")
test_df=pd.read_csv("test.csv")

In [96]:
train_df.head()

id keyword location                                               text  \
0   1     NaN      NaN  Our Deeds are the Reason of this #earthquake M...   
1   4     NaN      NaN             Forest fire near La Ronge Sask. Canada   
2   5     NaN      NaN  All residents asked to 'shelter in place' are ...   
3   6     NaN      NaN  13,000 people receive #wildfires evacuation or...   
4   7     NaN      NaN  Just got sent this photo from Ruby #Alaska as ...   

   target  
0       1  
1       1  
2       1  
3       1  
4       1

In [97]:
train_data_shuffled=train_df.sample(frac=1, random_state=42)

In [98]:
train_data_shuffled

id       keyword                        location  \
2644   3796   destruction                             NaN   
2227   3185        deluge                             NaN   
5448   7769        police                              UK   
132     191    aftershock                             NaN   
6845   9810        trauma           Montgomery County, MD   
...     ...           ...                             ...   
5226   7470  obliteration                         Merica!   
5390   7691         panic                             NaN   
860    1242         blood                             NaN   
7603  10862           NaN                             NaN   
7270  10409     whirlwind  Stamford & Cork (& Shropshire)   

                                                   text  target  
2644  So you have a new weapon that can cause un-ima...       1  
2227  The f$&amp;@ing things I do for #GISHWHES Just...       0  
5448  DT @georgegalloway: RT @Galloway4Mayor: ‰ÛÏThe...       1  
132   Aftershock back to school kick off was great. ...       0  
6845  in response to trauma Children of Addicts deve...       0  
...                                                 ...     ...  
5226  @Eganator2000 There aren't many Obliteration s...       0  
5390  just had a panic attack bc I don't have enough...       0  
860   Omron HEM-712C Automatic Blood Pressure Monito...       0  
7603  Officials say a quarantine is in place at an A...       1  
7270  I moved to England five years ago today. What ...       1  

[7613 rows x 5 columns]

In [99]:
#Test dataframe looks like:
test_df.head()

id keyword location                                               text
0   0     NaN      NaN                 Just happened a terrible car crash
1   2     NaN      NaN  Heard about #earthquake is different cities, s...
2   3     NaN      NaN  there is a forest fire at spot pond, geese are...
3   9     NaN      NaN           Apocalypse lighting. #Spokane #wildfires
4  11     NaN      NaN      Typhoon Soudelor kills 28 in China and Taiwan

In [100]:
train_df.target.value_counts()

0    4342
1    3271
Name: target, dtype: int64

In [101]:
#How many total number of samples
len(train_df), len(test_df)

(7613, 3263)

In [102]:
#Let's visualize some random training samples
import random
random_index = random.randint(0,len(train_df)-5)
for row in train_data_shuffled[['text','target']][random_index:random_index+5].itertuples():
  _,text, target=row
  print(f"Target: {target}", "(real disaster)" if target >0 else "(not real disaster)")
  print(f"text:\n{text}\n")
  print("---\n")

Target: 1 (real disaster)
text:
Wreckage 'Conclusively Confirmed' as From MH370: Malaysia PM: Investigators and the families of those who were... http://t.co/MSsq0sVnBM

---

Target: 1 (real disaster)
text:
Russian 'food crematoria' provoke outrage amid crisis famine memories - Yahoo News http://t.co/6siiRlnV6z

---

Target: 1 (real disaster)
text:
The ol' meltdown victory for the Mets.

---

Target: 1 (real disaster)
text:
More Natural Disaster Research Urgent http://t.co/5Cm0LfZhxn via #JakartaPost

---

Target: 0 (not real disaster)
text:
I have been bleeding into this typewriter all day but so far all I've written is a bunch of gunk.

---



### Split data into training and validation sets



In [103]:
from sklearn.model_selection import train_test_split

In [104]:
train_sentences, val_sentences, train_labels, val_labels=train_test_split(train_data_shuffled['text'].to_numpy(),
                                                                          train_data_shuffled['target'].to_numpy(),
                                                                          test_size=0.1,
                                                                          random_state=42)

In [105]:
#Check the lengths
len(train_sentences), len(train_labels), len(val_sentences), len(val_labels)

(6851, 6851, 762, 762)

## Converting words into numbers

First thing while building a model is to convert your text into numbers


Tokenization VS Embedding
Tkenization - word level and character level. Direct apping of a token.

Embedding - every word gets turned into a vector and we can define size of the vector. Embeddings can learn as our model trains



Text vectorization(tokenization)

In [106]:
import tensorflow as tf
from tensorflow.keras.layers.experimental.preprocessing import TextVectorization

In [107]:
#Use the default text vectorization parameters
text_vectoizer= TextVectorization(max_tokens=None, #Defines how many words in our vocab
                               standardize= "lower_and_strip_punctuation",
                               split="whitespace",
                               ngrams=None,
                               output_mode='int',
                               output_sequence_length=None) #how long do you want your sequences to be
                               #pad_to_max_tokens=True)

In [108]:
train_sentences[0].split()

['@mogacola', '@zamtriossu', 'i', 'screamed', 'after', 'hitting', 'tweet']

In [109]:
#Find the average number of tokens(words) in the training tweets
round(sum([len(i.split()) for i in train_sentences])/len(train_sentences))

15

In [110]:
max_vocab_length= 10000 #max no of words to have in our vocab
max_length=15 #Max length our sequences will be (e.g. how many words from a Tweet does a model see)

text_vectorizer=TextVectorization(max_tokens=max_vocab_length,
                                     output_mode="int",
                                     output_sequence_length=max_length)

In [111]:
#Fit the text vectorizer to the training text
text_vectorizer.adapt(train_sentences)


In [112]:
train_sentences[:10]

array(['@mogacola @zamtriossu i screamed after hitting tweet',
       'Imagine getting flattened by Kurt Zouma',
       '@Gurmeetramrahim #MSGDoing111WelfareWorks Green S welfare force ke appx 65000 members har time disaster victim ki help ke liye tyar hai....',
       "@shakjn @C7 @Magnums im shaking in fear he's gonna hack the planet",
       'Somehow find you and I collide http://t.co/Ee8RpOahPk',
       '@EvaHanderek @MarleyKnysh great times until the bus driver held us hostage in the mall parking lot lmfao',
       'destroy the free fandom honestly',
       'Weapons stolen from National Guard Armory in New Albany still missing #Gunsense http://t.co/lKNU8902JE',
       '@wfaaweather Pete when will the heat wave pass? Is it really going to be mid month? Frisco Boy Scouts have a canoe trip in Okla.',
       'Patient-reported outcomes in long-term survivors of metastatic colorectal cancer - British Journal of Surgery http://t.co/5Yl4DC1Tqt'],
      dtype=object)

In [113]:
#Create a sample sentence and tokenize it
sample_sentence="There is a floow in my street!"
text_vectorizer([sample_sentence])

<tf.Tensor: shape=(1, 15), dtype=int64, numpy=
array([[ 74,   9,   3,   1,   4,  13, 698,   0,   0,   0,   0,   0,   0,
          0,   0]])>

In [114]:
random_sentence=random.choice(train_sentences)
print(random_sentence)
vectorized_random_sentence=text_vectorizer([random_sentence])
print(f"Random Sentence: {random_sentence}\nVectoized Random Sentence: {vectorized_random_sentence}")

FedEx no longer will ship potential bioterror pathogens - FedEx Corp. (NYSE: FDX) will no longer deliver packages ... http://t.co/2kdq56xTWs
Random Sentence: FedEx no longer will ship potential bioterror pathogens - FedEx Corp. (NYSE: FDX) will no longer deliver packages ... http://t.co/2kdq56xTWs
Vectoized Random Sentence: [[ 577   40  600   38  810 1615  609 1801  577 5912    1    1   38   40
   600]]


In [115]:
words_in_vocab=text_vectorizer.get_vocabulary()
top_5_words=words_in_vocab[:5]
botton_5_words=words_in_vocab[-5:]

In [116]:
words_in_vocab,top_5_words,botton_5_words

(['',
  '[UNK]',
  'the',
  'a',
  'in',
  'to',
  'of',
  'and',
  'i',
  'is',
  'for',
  'on',
  'you',
  'my',
  'with',
  'it',
  'that',
  'at',
  'by',
  'this',
  'from',
  'be',
  'are',
  'was',
  'have',
  'like',
  'as',
  'up',
  'so',
  'just',
  'but',
  'me',
  'im',
  'your',
  'not',
  'amp',
  'out',
  'its',
  'will',
  'an',
  'no',
  'has',
  'fire',
  'after',
  'all',
  'when',
  'we',
  'if',
  'now',
  'via',
  'new',
  'more',
  'get',
  'or',
  'about',
  'what',
  'he',
  'people',
  'news',
  'been',
  'over',
  'one',
  'how',
  'dont',
  'they',
  'who',
  'into',
  'were',
  'do',
  'us',
  '2',
  'can',
  'video',
  'emergency',
  'there',
  'disaster',
  'than',
  'police',
  'would',
  'his',
  'still',
  'her',
  'some',
  'body',
  'storm',
  'crash',
  'burning',
  'suicide',
  'back',
  'man',
  'california',
  'why',
  'time',
  'them',
  'had',
  'buildings',
  'rt',
  'first',
  'cant',
  'see',
  'got',
  'day',
  'off',
  'our',
  'going',
 

### Creating an embedding using an embedding layer

To make our embedding, we're going to use the TF's embedding layer.

The parameters we care the most about our embedding layers are:
* input_dim= sie of our vocab
* output_dim= size of the output embedding vector. A value of a 100 will mean that each token will be represented as a vector of 100 long length
* input_length= length of sequences being passed to the embedding layer
*

In [117]:
from tensorflow.keras import layers

In [118]:
embedding=layers.Embedding(input_dim=max_vocab_length,
                           output_dim=128,
                           input_length=max_length)

In [119]:
embedding

In [120]:
#Get a random sentence from the training set
random_sentence=random.choice(train_sentences)
print(f"Original Sentence:{random_sentence}\
      \nEmbedded Sentence")

sample_embedding=embedding(text_vectorizer([random_sentence]))
sample_embedding

Original Sentence:Ancient Mayan Tablet Found in Jungle Temple http://t.co/qp6q8RS8ON      
Embedded Sentence


<tf.Tensor: shape=(1, 15, 128), dtype=float32, numpy=
array([[[-0.03305274,  0.03334713, -0.0422186 , ..., -0.0002015 ,
         -0.02461776, -0.03663777],
        [-0.03749834,  0.04993585,  0.0281971 , ..., -0.01925508,
          0.00739387, -0.04485953],
        [ 0.02407706, -0.0220372 , -0.00616293, ..., -0.00148871,
          0.00904542,  0.00793977],
        ...,
        [ 0.01678229, -0.04126339,  0.04923167, ..., -0.01411662,
         -0.02210027, -0.00361538],
        [ 0.01678229, -0.04126339,  0.04923167, ..., -0.01411662,
         -0.02210027, -0.00361538],
        [ 0.01678229, -0.04126339,  0.04923167, ..., -0.01411662,
         -0.02210027, -0.00361538]]], dtype=float32)>

In [121]:
#Check out a single token's embedding
sample_embedding[0][0], sample_embedding[0][0].shape, random_sentence[0]

(<tf.Tensor: shape=(128,), dtype=float32, numpy=
 array([-0.03305274,  0.03334713, -0.0422186 , -0.01651434, -0.01004869,
         0.00807239,  0.02143629,  0.04050611, -0.0488528 ,  0.04384295,
        -0.04994569, -0.02975096, -0.04748983,  0.03848847,  0.014861  ,
        -0.03664464,  0.02235797, -0.01168202, -0.00961262, -0.02008259,
         0.04554153,  0.04856726,  0.000729  ,  0.015517  ,  0.02172233,
         0.01956419, -0.00673329, -0.01454289, -0.02853456, -0.01421569,
        -0.03547049, -0.04265514,  0.04614327, -0.02024713,  0.0492197 ,
         0.01474769, -0.03769908, -0.04338888,  0.00069172,  0.03630065,
         0.01816435,  0.01300832, -0.01224078,  0.04164369, -0.03761123,
        -0.03906231, -0.02251348,  0.01014551, -0.01259303,  0.01133149,
         0.02600336,  0.02457358, -0.03501425,  0.04379206,  0.04179703,
        -0.01283264,  0.02588114, -0.03014401, -0.0332365 , -0.00388657,
         0.03525729,  0.01430574, -0.03992382,  0.01723776,  0.0177853 ,
  

##Modelling a text dataset(running a series of experiments)

* Model 0: Naive Bayes with Tokenization
* Model 1: Feed-forward Neural Network(Dense Model)
* Model 2: LSTM Model(RNN)
* Model 3: GRU Model
* Moel 4: Bidirectional LSTM
* Model 5 : 1D Convolutional Layer
* model 6: Tensorflow hub pretrained feature extraction (using transfer learning)
* Model 7 : Same as model 6 with 10% of data

How are we going to approach all of these:
Use the standard steps in modelling with tensorflow

* Create->build->fit->Evaluate



### Model 0

To create a baseline, we'll use sklearn's Naive Bayes using Tf-IDF to convert our words to numbers

It is a good practice to use non-DL Algos as a baseline because of their speed and then later use DL to see if you can improve upon them

In [122]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline

In [123]:
model_0=Pipeline([
    ("tfidf",TfidfVectorizer()),
    ("clf",MultinomialNB())
])

model_0.fit(train_sentences, train_labels)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('clf', MultinomialNB())])

In [124]:
#Evaluate the baseline Model
baseline_score = model_0.score(val_sentences, val_labels)
print(f"our baseline model achieves an accuracy of : {baseline_score*100:.2f}%")

our baseline model achieves an accuracy of : 79.27%


In [125]:
train_df.target.value_counts

<bound method IndexOpsMixin.value_counts of 0       1
1       1
2       1
3       1
4       1
       ..
7608    1
7609    1
7610    1
7611    1
7612    1
Name: target, Length: 7613, dtype: int64>

In [126]:
#Make predictions
baseline_preds= model_0.predict(val_sentences)
baseline_preds[:20]

array([1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1])

### Create an evaluation function for our model experiments

We could evaluate all of our model's predictions with different metrics every time.
Calculate:
* Accuracy
* Precision
* Recall
* F1 score


In [127]:
#Function to evaluate the above metrics
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

def calculate_results(y_true, y_pred):
  """
  Calculated model accuracy, precision, recall and f1 score of a binary classification model
  """
  #Calculate model accuracy
  model_accuracy=accuracy_score(y_true, y_pred) * 100
  #Calculate model precision, recall and f1 score using the"weighted average"
  model_precision, model_recall, model_f1, _ = precision_recall_fscore_support(y_true, y_pred,average="weighted" )
  model_results={'accuracy':model_accuracy,
                 'precision': model_precision,
                 'recall': model_recall,
                 'f1-score':model_f1}
  return model_results

In [128]:
#Get baseline results
baseline_results=calculate_results(y_true=val_labels,
                                   y_pred=baseline_preds)

In [129]:
baseline_results['accuracy']

79.26509186351706

In [130]:
baseline_results

{'accuracy': 79.26509186351706,
 'precision': 0.8111390004213173,
 'recall': 0.7926509186351706,
 'f1-score': 0.7862189758049549}

## Model 1: A simple Dense Model

In [131]:
#Create a tensorflow callback
from helper_functions import create_tensorboard_callback

#Create a directory to save tensorboard logs
SAVE_DIR="model_logs"


In [132]:
#Build model with functional API
from tensorflow.keras import layers

inputs=layers.Input(shape=(1,), dtype=tf.string) #Inputs are 1 dimensional
x= text_vectorizer(inputs) #Turn the input text into numbers
x= embedding(x) #Create an embedding of vctorized embeddings
x=layers.GlobalAveragePooling1D()(x)
outputs=layers.Dense(1, activation='sigmoid')(x)

model_1=tf.keras.Model(inputs, outputs, name="Model_1_dense")

In [133]:
model_1.summary()

Model: "Model_1_dense"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_16 (InputLayer)       [(None, 1)]               0         
                                                                 
 text_vectorization_3 (TextV  (None, 15)               0         
 ectorization)                                                   
                                                                 
 embedding_1 (Embedding)     (None, 15, 128)           1280000   
                                                                 
 global_average_pooling1d_1   (None, 128)              0         
 (GlobalAveragePooling1D)                                        
                                                                 
 dense_16 (Dense)            (None, 1)                 129       
                                                                 
Total params: 1,280,129
Trainable params: 1,280,129
N

In [134]:
#Compile model
model_1.compile(loss='binary_crossentropy',
                optimizer=tf.keras.optimizers.Adam(),
                metrics=['accuracy'])

In [135]:
model_1_history=model_1.fit(x=train_sentences,
                            y=train_labels,
                            epochs=5,
                            validation_data=(val_sentences,val_labels),
                            callbacks=[create_tensorboard_callback(dir_name=SAVE_DIR,
                                                                   experiment_name="model_1_dense")])

Saving TensorBoard log files to: model_logs/model_1_dense/20230616-031253
Epoch 1/5
215/215 [==============================] - 8s 31ms/step - loss: 0.6107 - accuracy: 0.6949 - val_loss: 0.5365 - val_accuracy: 0.7598
Epoch 2/5
215/215 [==============================] - 9s 42ms/step - loss: 0.4408 - accuracy: 0.8203 - val_loss: 0.4684 - val_accuracy: 0.7822
Epoch 3/5
215/215 [==============================] - 8s 36ms/step - loss: 0.3470 - accuracy: 0.8619 - val_loss: 0.4617 - val_accuracy: 0.7940
Epoch 4/5
215/215 [==============================] - 10s 47ms/step - loss: 0.2837 - accuracy: 0.8917 - val_loss: 0.4646 - val_accuracy: 0.7861
Epoch 5/5
215/215 [==============================] - 8s 39ms/step - loss: 0.2377 - accuracy: 0.9115 - val_loss: 0.4793 - val_accuracy: 0.7822


In [136]:
model_1.evaluate(val_sentences, val_labels)

24/24 [==============================] - 0s 4ms/step - loss: 0.4793 - accuracy: 0.7822


[0.4793274998664856, 0.7821522355079651]

In [137]:
model_1_pred_probs=model_1.predict(val_sentences)

24/24 [==============================] - 1s 4ms/step


In [138]:
model_1_pred_probs.shape

(762, 1)

In [139]:
#calculate_results(val_labels, model_1_pred_probs)

ValueError: ignored

In [145]:
val_labels

array([0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,

In [146]:
#Convert Model_prediction Probabs into label formats
model_1_preds=tf.squeeze(tf.round(model_1_pred_probs))

In [147]:
model_1_preds

<tf.Tensor: shape=(762,), dtype=float32, numpy=
array([0., 1., 1., 0., 0., 1., 1., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 1., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 1., 1., 1., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0.,
       0., 1., 1., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1.,
       0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 1., 1., 1., 1., 0.,
       1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       1., 1., 1., 0., 1., 0., 0., 0., 1., 1., 0., 1., 1., 1., 1., 0., 0.,
       1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0.,
       0., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0

In [148]:
model_1_results=calculate_results(y_true=val_labels,
                                  y_pred=model_1_preds)

In [149]:
model_1_results

{'accuracy': 78.21522309711287,
 'precision': 0.7864332425219001,
 'recall': 0.7821522309711286,
 'f1-score': 0.7792361147360404}

In [150]:
baseline_results

{'accuracy': 79.26509186351706,
 'precision': 0.8111390004213173,
 'recall': 0.7926509186351706,
 'f1-score': 0.7862189758049549}

In [151]:
import numpy as np
np.array(list(model_1_results.values()))> np.array(list(baseline_results.values()))

array([False, False, False, False])

## Visualize the learned embeddings


In [ ]:
#Get the vocabulary from the text vectorization layer
words_in_vocab = text_vectorizer.get_vocabulary()

In [ ]:
len(words_in_vocab), words_in_vocab[:10]

In [ ]:
# Model 1 summary
model_1.summary()

In [ ]:
#Get the weight matrix of the embedding layers
#These are numerical representation of our numerical datawhich are trained for 5 epochs

embed_weights=model_1.get_layer("embedding").get_weights()[0]
embed_weights

In [ ]:
print(embed_weights.shape)

Now we've got the embedding matrix our model has learned to represent tokens, let's see how we can visualize it

To do so, tensorflow has a tool called Projector

In [ ]:
# # Code below is adapted from: https://www.tensorflow.org/tutorials/text/word_embeddings#retrieve_the_trained_word_embeddings_and_save_them_to_disk
import io

# Create output writers
out_v = io.open("embedding_vectors.tsv", "w", encoding="utf-8")
out_m = io.open("embedding_metadata.tsv", "w", encoding="utf-8")

# Write embedding vectors and words to file
for num, word in enumerate(words_in_vocab):
  if num == 0:
     continue # skip padding token
  vec = embed_weights[num]
  out_m.write(word + "\n") # write words to file
  out_v.write("\t".join([str(x) for x in vec]) + "\n") # write corresponding word vector to file
out_v.close()
out_m.close()

In [ ]:
# Download files locally to upload to Embedding Projector
try:
  from google.colab import files
except ImportError:
  pass
else:
  files.download("embedding_vectors.tsv")
  files.download("embedding_metadata.tsv")

## Recurrent Neural Networks(RNNs)

the premise of the Recurrent Neural Networs is to use the representation of the previous input to aid the representation of the later input

RNNs are used for sequence data (this example is a sequence of text)

 üìñ Resources:

MIT Deep Learning Lecture on Recurrent Neural Networks - explains the background of recurrent neural networks and introduces LSTMs.
The Unreasonable Effectiveness of Recurrent Neural Networks by Andrej Karpathy - demonstrates the power of RNN's with examples generating various sequences.
Understanding LSTMs by Chris Olah - an in-depth (and technical) look at the mechanics of the LSTM cell, possibly the most popular RNN building block.

### Model 2: LSTM

LSTM= long short term memory

Our structure of an RNN Looks like this

Input(text)-> Tokenize -> Embedding -> Layers(RNNs/Dense)->output(label probability)

In [ ]:
#Create an LSTM Model
from tensorflow.keras import layers
inputs= layers.Input(shape=(1,), dtype=tf.string)
x=text_vectorizer(inputs)
x= embedding(x)
print(x.shape)
x=layers.LSTM(64, return_sequences=True)(x) #64 is hidden units
#When you a stacking RNN Cells together, you need to return sequences=true
print(x.shape)
x= layers.LSTM(64)(x)
print(x.shape)
x= layers.Dense(64, activation='relu')(x)
print(x.shape)
outputs=layers.Dense(1, activation='sigmoid')(x)

model_2= tf.keras.Model(inputs, outputs, name="model_2_LSTM")


In [ ]:
#Create an LSTM Model
from tensorflow.keras import layers
inputs= layers.Input(shape=(1,), dtype=tf.string)
x=text_vectorizer(inputs)
x= embedding(x)
#print(x.shape)
#x=layers.LSTM(64, return_sequences=True)(x) #64 is hidden units
#When you a stacking RNN Cells together, you need to return sequences=true
#print(x.shape)
x= layers.LSTM(64)(x)
#print(x.shape)
#x= layers.Dense(64, activation='relu')(x)
#print(x.shape)
outputs=layers.Dense(1, activation='sigmoid')(x)

model_2= tf.keras.Model(inputs, outputs, name="model_2_LSTM")


In [ ]:
model_2.summary()

###The default activation function for RNNs is TanH

In [ ]:
#Complie the model
model_2.compile(loss='binary_crossentropy',
                optimizer=tf.keras.optimizers.Adam(),
                metrics=['accuracy'])

In [ ]:
history_model_2_LSTM=model_2.fit(train_sentences,
                                 train_labels,
                                 epochs=5,
                                 validation_data=(val_sentences, val_labels),
                                 callbacks=[create_tensorboard_callback(dir_name=SAVE_DIR,
                                                                        experiment_name="model_2_LSTM")])

In [ ]:
model_2_pred_probs=model_2.predict(val_sentences)
model_2_pred_probs[:10]

In [ ]:
#Convert the probabs to pred
model_2_preds=tf.squeeze(tf.round(model_2_pred_probs))

In [ ]:
model_2_preds


In [ ]:
model_2_results=calculate_results(y_true=val_labels,
                                  y_pred=model_2_preds)

In [ ]:
model_2_results

In [ ]:
baseline_results


### Model 3: GRU

Similar to LSTM but has less params

In [ ]:
from tensorflow.keras import layers
inputs= tf.keras.Input(shape=(1,), dtype=tf.string)
x = text_vectorizer(inputs)

x=embedding(x)

x = tf.keras.layers.GRU(64, return_sequences=True)(x) #if you want to stack recurrent layers on top of each other, you need to use return_sequences=True
x=layers.LSTM(64, return_sequences=True)(x)
x=layers.GRU(64)(x)

x=layers.Dense(64, activation='relu')(x)
outputs=layers.Dense(1, activation='sigmoid')(x)
model_3=tf.keras.Model(inputs, outputs, name="Model_3_GRU")


In [ ]:
from tensorflow.keras import layers
inputs= tf.keras.Input(shape=(1,), dtype=tf.string)
x = text_vectorizer(inputs)

x=embedding(x)

x = tf.keras.layers.GRU(64)(x) #if you want to stack recurrent layers on top of each other, you need to use return_sequences=True
#x=layers.LSTM(64, return_sequences=True)(x)
#x=layers.GRU(64)(x)

x=layers.Dense(64, activation='relu')(x)
outputs=layers.Dense(1, activation='sigmoid')(x)
model_3=tf.keras.Model(inputs, outputs, name="Model_3_GRU")


In [ ]:
model_3.summary()

In [ ]:
model_3.compile(loss='binary_crossentropy',
                optimizer=tf.keras.optimizers.Adam(),
                metrics=['accuracy'])

In [ ]:
history_model_3_GRU=model_3.fit(train_sentences,
                                train_labels,
                                validation_data=(val_sentences, val_labels),
                                epochs=5,
                                callbacks=[create_tensorboard_callback(dir_name=SAVE_DIR,
                                                                      experiment_name='model_name_GRU')])

In [141]:
model_3_pred_probs=model_3.predict(val_sentences)
model_3_pred_probs[:10]

24/24 [==============================] - 1s 8ms/step


array([[6.2693977e-03],
       [5.5768818e-01],
       [9.9999583e-01],
       [1.0364279e-01],
       [1.1872800e-05],
       [9.9975604e-01],
       [8.8811561e-02],
       [9.9999785e-01],
       [9.9999595e-01],
       [6.8013978e-01]], dtype=float32)

In [142]:
model_3_preds=tf.squeeze(tf.round(model_3_pred_probs))
model_3_preds[:10]

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([0., 1., 1., 0., 0., 1., 0., 1., 1., 1.], dtype=float32)>

In [143]:
calculate_results(y_true=val_labels,
                  y_pred=model_3_preds)

{'accuracy': 76.24671916010499,
 'precision': 0.7639905060800456,
 'recall': 0.7624671916010499,
 'f1-score': 0.7602456873168202}

In [144]:
baseline_results

{'accuracy': 79.26509186351706,
 'precision': 0.8111390004213173,
 'recall': 0.7926509186351706,
 'f1-score': 0.7862189758049549}

### Model_4 : Bidirectional LSTM

Normal RNNs go from left to right..
Bidirectional RNNs go from left to right as well as right to left




In [159]:
from tensorflow.keras import layers
inputs=layers.Input(shape=(1,), dtype=tf.string)
x= text_vectorizer(inputs)

x= embedding(x)

x=layers.Bidirectional(layers.LSTM(64))(x)
#print(x.shape) #Doubles the value of the shape...as the cell is bidirectional
#x=layers.Bidirectional(layers.GRU(64))(x)

outputs=layers.Dense(1, activation='sigmoid')(x)

model_4=tf.keras.Model(inputs, outputs, name='model_4_bidirectional')

In [160]:
model_4.summary()

Model: "model_4_bidirectional"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_22 (InputLayer)       [(None, 1)]               0         
                                                                 
 text_vectorization_3 (TextV  (None, 15)               0         
 ectorization)                                                   
                                                                 
 embedding_1 (Embedding)     (None, 15, 128)           1280000   
                                                                 
 bidirectional_6 (Bidirectio  (None, 128)              98816     
 nal)                                                            
                                                                 
 dense_20 (Dense)            (None, 1)                 129       
                                                                 
Total params: 1,378,945
Trainable params: 1,3

In [161]:
model_4.compile(loss='binary_crossentropy',
                metrics=['accuracy'],
                optimizer=tf.keras.optimizers.Adam())

In [162]:
history_4_bidirectional=model_4.fit(train_sentences,
                                    train_labels,
                                    validation_data=(val_sentences, val_labels),
                                    epochs=5,
                                    callbacks=[create_tensorboard_callback(dir_name=SAVE_DIR,
                                                                           experiment_name='model_4_bidirectional')])

Saving TensorBoard log files to: model_logs/model_4_bidirectional/20230616-034334
Epoch 1/5
215/215 [==============================] - 17s 54ms/step - loss: 0.2152 - accuracy: 0.9225 - val_loss: 0.5480 - val_accuracy: 0.7835
Epoch 2/5
215/215 [==============================] - 11s 49ms/step - loss: 0.1549 - accuracy: 0.9429 - val_loss: 0.6283 - val_accuracy: 0.7822
Epoch 3/5
215/215 [==============================] - 10s 48ms/step - loss: 0.1271 - accuracy: 0.9514 - val_loss: 0.7197 - val_accuracy: 0.7743
Epoch 4/5
215/215 [==============================] - 9s 43ms/step - loss: 0.1084 - accuracy: 0.9574 - val_loss: 0.7231 - val_accuracy: 0.7769
Epoch 5/5
215/215 [==============================] - 14s 64ms/step - loss: 0.0892 - accuracy: 0.9654 - val_loss: 0.9359 - val_accuracy: 0.7677


In [163]:
model_4_pred_probs=model_4.predict(val_sentences)
model_4_pred_probs[:10]

24/24 [==============================] - 4s 8ms/step


array([[2.1251854e-01],
       [9.0274268e-01],
       [9.9991882e-01],
       [5.6247890e-02],
       [1.3182372e-04],
       [9.9746835e-01],
       [9.1958749e-01],
       [9.9996579e-01],
       [9.9990803e-01],
       [5.2167481e-01]], dtype=float32)

In [164]:
model_4_preds=tf.squeeze(tf.round(model_4_pred_probs))
model_4_preds

<tf.Tensor: shape=(762,), dtype=float32, numpy=
array([0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 1., 1., 1., 0., 1., 0.,
       0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 1., 0., 1., 1., 1., 0.,
       1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 1., 1., 0., 1., 0., 1., 1., 0., 1., 1., 1., 1., 0.,
       0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 0.,
       0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 1., 1., 1., 0.,
       1., 0., 0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 1., 1.,
       1., 1., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 1., 1., 1., 0., 0.,
       1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0.,
       0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0

In [169]:
model_4_results=calculate_results(y_true=val_labels,
                y_pred=model_4_preds)

In [170]:
model_4_results

{'accuracy': 76.77165354330708,
 'precision': 0.7681410880728078,
 'recall': 0.7677165354330708,
 'f1-score': 0.7662770891654436}

In [171]:
baseline_results

{'accuracy': 79.26509186351706,
 'precision': 0.8111390004213173,
 'recall': 0.7926509186351706,
 'f1-score': 0.7862189758049549}

## Convolutional Neural Networks for text and other types of sequences

We've used CNN for images bit typically images are 2D(HxW)...however the text data is 1D

previously we used Conv2D for our image data...but now we will use conv1d

Typical structure of Conv1D model for sequences :

Inputs(text)-> tokenization-> embedding-> layers(Conv1D)->Pooling-> Output(class Probabs)

### Model 5: Conv1D

In [172]:
from tensorflow.keras import layers

embedding_test=embedding(text_vectorizer(["THis is a test sentence"]))
conv1d= layers.Conv1D(filters=32,
                      kernel_size=5,
                      activation='relu',
                      padding='valid') #Default=valid, the outpus is smaller than the 'same' shape than the input

conv_1d_output=conv1d(embedding_test)
max_pool=layers.GlobalMaxPool1D()
max_pool_output=max_pool(conv_1d_output) #Get the mot imporetant features...get the feature with hightest value

embedding_test.shape, conv_1d_output.shape, max_pool_output.shape

(TensorShape([1, 15, 128]), TensorShape([1, 11, 32]), TensorShape([1, 32]))

In [173]:
#Where is the 11 coming from. THis is because we are using padding as valid and kernel size as 5

In [174]:
embedding_test

<tf.Tensor: shape=(1, 15, 128), dtype=float32, numpy=
array([[[-0.00657184, -0.06535109,  0.01560264, ...,  0.02140128,
          0.00618981, -0.01930427],
        [ 0.00916248, -0.03951672, -0.00012985, ...,  0.04411504,
         -0.02060145, -0.00520738],
        [ 0.05060086, -0.00938471, -0.0006804 , ..., -0.00180441,
          0.00540061, -0.01756253],
        ...,
        [ 0.02859491, -0.04157931,  0.02600376, ..., -0.00904637,
         -0.0216876 , -0.02038047],
        [ 0.02859491, -0.04157931,  0.02600376, ..., -0.00904637,
         -0.0216876 , -0.02038047],
        [ 0.02859491, -0.04157931,  0.02600376, ..., -0.00904637,
         -0.0216876 , -0.02038047]]], dtype=float32)>

In [175]:
conv_1d_output

<tf.Tensor: shape=(1, 11, 32), dtype=float32, numpy=
array([[[0.        , 0.        , 0.03284881, 0.        , 0.01117422,
         0.        , 0.        , 0.        , 0.01953866, 0.        ,
         0.05711921, 0.00162833, 0.05206185, 0.        , 0.        ,
         0.02032651, 0.04092628, 0.        , 0.        , 0.        ,
         0.0633163 , 0.        , 0.        , 0.        , 0.        ,
         0.00527028, 0.02214666, 0.05921314, 0.03058301, 0.00192783,
         0.        , 0.10612602],
        [0.        , 0.04462915, 0.        , 0.04470368, 0.02211461,
         0.02406022, 0.04909075, 0.01351929, 0.        , 0.        ,
         0.01432387, 0.04530457, 0.0125358 , 0.06134007, 0.00450303,
         0.        , 0.07006411, 0.        , 0.        , 0.        ,
         0.        , 0.00089449, 0.00475501, 0.        , 0.        ,
         0.0323413 , 0.        , 0.01594213, 0.        , 0.02559575,
         0.        , 0.08820157],
        [0.        , 0.02307468, 0.03304613, 0.0612

In [176]:
max_pool_output

<tf.Tensor: shape=(1, 32), dtype=float32, numpy=
array([[0.02127084, 0.0764298 , 0.03304613, 0.07097452, 0.02211461,
        0.02406022, 0.08851391, 0.01351929, 0.05630821, 0.        ,
        0.05711921, 0.09230591, 0.09395298, 0.06134007, 0.02764263,
        0.05923818, 0.07006411, 0.        , 0.02295003, 0.00917987,
        0.09346423, 0.01964616, 0.00784606, 0.03471003, 0.00034138,
        0.05131255, 0.07279582, 0.05921314, 0.04464867, 0.02910609,
        0.02802909, 0.10612602]], dtype=float32)>

In [180]:
from tensorflow.keras import layers

inputs= layers.Input(shape=(1,),dtype=tf.string)
x= text_vectorizer(inputs)
x= embedding(x)

x= layers.Conv1D(filters=64,
                 kernel_size=5,
                 strides=1,
                 activation='relu',
                 padding='valid')(x)

x= layers.GlobalMaxPool1D()(x)

outputs=layers.Dense(1, activation='sigmoid')(x)
model_5=tf.keras.Model(inputs, outputs,name='model_5_conv_1_d')

In [181]:
model_5.summary()

Model: "model_5_conv_1_d"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_26 (InputLayer)       [(None, 1)]               0         
                                                                 
 text_vectorization_3 (TextV  (None, 15)               0         
 ectorization)                                                   
                                                                 
 embedding_1 (Embedding)     (None, 15, 128)           1280000   
                                                                 
 conv1d_1 (Conv1D)           (None, 11, 64)            41024     
                                                                 
 global_max_pooling1d_1 (Glo  (None, 64)               0         
 balMaxPooling1D)                                                
                                                                 
 dense_21 (Dense)            (None, 1)            

In [182]:
model_5.compile(loss='binary_crossentropy',
                optimizer=tf.keras.optimizers.Adam(),
                metrics=['accuracy'])

In [183]:
model_5_history_Conv1D=model_5.fit(train_sentences,
                                   train_labels,
                                   validation_data=(val_sentences, val_labels),
                                   epochs=5,
                                   callbacks=[create_tensorboard_callback(dir_name=SAVE_DIR,
                                                                          experiment_name="model_5_Conv1D")])

Saving TensorBoard log files to: model_logs/model_5_Conv1D/20230616-042051
Epoch 1/5
215/215 [==============================] - 11s 43ms/step - loss: 0.1539 - accuracy: 0.9475 - val_loss: 0.7620 - val_accuracy: 0.7874
Epoch 2/5
215/215 [==============================] - 8s 38ms/step - loss: 0.0991 - accuracy: 0.9622 - val_loss: 0.9322 - val_accuracy: 0.7743
Epoch 3/5
215/215 [==============================] - 10s 48ms/step - loss: 0.0797 - accuracy: 0.9686 - val_loss: 0.9887 - val_accuracy: 0.7756
Epoch 4/5
215/215 [==============================] - 8s 37ms/step - loss: 0.0710 - accuracy: 0.9737 - val_loss: 1.0264 - val_accuracy: 0.7651
Epoch 5/5
215/215 [==============================] - 8s 39ms/step - loss: 0.0608 - accuracy: 0.9765 - val_loss: 1.0954 - val_accuracy: 0.7559


In [184]:
model_5_pred_probs=model_5.predict(val_sentences)
model_5_pred_probs

24/24 [==============================] - 0s 3ms/step


array([[5.35339475e-01],
       [9.45296705e-01],
       [9.99912858e-01],
       [3.07707358e-02],
       [2.74930380e-06],
       [9.97653365e-01],
       [9.95280623e-01],
       [9.99791980e-01],
       [9.99997795e-01],
       [7.12915719e-01],
       [1.83202886e-07],
       [8.84876192e-01],
       [4.92535000e-05],
       [3.29502553e-01],
       [1.14479315e-06],
       [1.76029466e-03],
       [4.56018955e-04],
       [7.32105036e-05],
       [8.97629466e-03],
       [9.87701893e-01],
       [9.26538348e-01],
       [1.29179507e-05],
       [9.99353051e-01],
       [1.63346238e-03],
       [9.99997556e-01],
       [1.00000000e+00],
       [8.14487401e-04],
       [1.10710898e-04],
       [1.01419271e-03],
       [8.37844491e-01],
       [4.41846512e-02],
       [1.26846935e-04],
       [1.84090540e-01],
       [4.46463143e-03],
       [5.05934022e-02],
       [4.98154283e-01],
       [9.99995708e-01],
       [1.04664445e-01],
       [1.23588955e-02],
       [9.99995887e-01],


In [185]:
model_5_preds=tf.squeeze(tf.round(model_5_pred_probs))
model_5_preds

<tf.Tensor: shape=(762,), dtype=float32, numpy=
array([1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 1., 1., 1., 0., 1., 0.,
       0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 1., 0., 1., 1., 1., 0.,
       1., 0., 0., 0., 1., 0., 1., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0.,
       0., 1., 1., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1.,
       0., 1., 0., 0., 1., 1., 0., 1., 0., 0., 1., 0., 1., 1., 1., 1., 0.,
       1., 1., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 1., 1.,
       1., 1., 1., 0., 1., 0., 0., 0., 1., 1., 0., 1., 1., 1., 1., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0.,
       0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0

In [186]:
calculate_results(y_true=val_labels,
                  y_pred=model_5_preds)

{'accuracy': 75.59055118110236,
 'precision': 0.7567160722556739,
 'recall': 0.7559055118110236,
 'f1-score': 0.7539595513230887}

In [187]:
baseline_results

{'accuracy': 79.26509186351706,
 'precision': 0.8111390004213173,
 'recall': 0.7926509186351706,
 'f1-score': 0.7862189758049549}

## Model 6: Tensorflow Hub pretrained Sentence Encoding

In [188]:
# Example of pretrained embedding with universal sentence encoder - https://tfhub.dev/google/universal-sentence-encoder/4
import tensorflow_hub as hub
embed = hub.load("https://tfhub.dev/google/universal-sentence-encoder/4") # load Universal Sentence Encoder
embed_samples = embed([sample_sentence,
                      "When you call the universal sentence encoder on a sentence, it turns it into numbers."])

print(embed_samples[0][:50])

tf.Tensor(
[-0.01648418  0.01238944 -0.03802393  0.0161351   0.01126495  0.03020511
 -0.03046945  0.06194782 -0.02105992 -0.03057138  0.00088417 -0.01712315
  0.02300225  0.13233913 -0.02402747 -0.04065575 -0.00783854 -0.01782105
  0.00084766 -0.06022933  0.03030975 -0.02432619  0.01335938 -0.00702189
 -0.03293562  0.01491862  0.06453035 -0.03094473 -0.02930314  0.05430475
 -0.04252576  0.03884935  0.05540232  0.04995463  0.01574395 -0.04668788
  0.06723309  0.07616691 -0.03243509 -0.09583163  0.0146003   0.05765746
 -0.05838085  0.08828382 -0.1043603  -0.03254436 -0.03735406 -0.04613885
  0.02244526 -0.0233586 ], shape=(50,), dtype=float32)


In [189]:
#Create keras layer using USE Pretrained Layer from tensorflow hub
sentence_encoder_layer= hub.KerasLayer("https://tfhub.dev/google/universal-sentence-encoder/4",
                                       input_shape=[],#output will be a 512 vector
                                       dtype=tf.string,
                                       trainable=False,
                                       name='USE')

In [191]:
#Create moled using the sequential api
model_6=tf.keras.Sequential([
    sentence_encoder_layer,
    #layers.Dense(64,activation='relu)
    layers.Dense(1, activation='sigmoid')
], name='mode_6_use')

#Complie
model_6.compile(loss='binary_crossentropy',
                optimizer=tf.keras.optimizers.Adam(),
                metrics=['accuracy'])

model_6.summary()

Model: "mode_6_use"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 USE (KerasLayer)            (None, 512)               256797824 
                                                                 
 dense_23 (Dense)            (None, 1)                 513       
                                                                 
Total params: 256,798,337
Trainable params: 513
Non-trainable params: 256,797,824
_________________________________________________________________


In [193]:
#Train a classifier on top of pretrianed embeddings
history_model_6=model_6.fit(train_sentences,
            train_labels,
            epochs=5,
            validation_data=(val_sentences, val_labels),
                            callbacks=[create_tensorboard_callback(dir_name=SAVE_DIR,
                                                                   experiment_name="tf_hub_sentnece_encoder")])

Saving TensorBoard log files to: model_logs/tf_hub_sentnece_encoder/20230616-051506
Epoch 1/5
215/215 [==============================] - 8s 19ms/step - loss: 0.6498 - accuracy: 0.7288 - val_loss: 0.6130 - val_accuracy: 0.7822
Epoch 2/5
215/215 [==============================] - 3s 13ms/step - loss: 0.5819 - accuracy: 0.7886 - val_loss: 0.5635 - val_accuracy: 0.7861
Epoch 3/5
215/215 [==============================] - 3s 13ms/step - loss: 0.5390 - accuracy: 0.7938 - val_loss: 0.5317 - val_accuracy: 0.7861
Epoch 4/5
215/215 [==============================] - 3s 15ms/step - loss: 0.5102 - accuracy: 0.7968 - val_loss: 0.5103 - val_accuracy: 0.7913
Epoch 5/5
215/215 [==============================] - 3s 16ms/step - loss: 0.4900 - accuracy: 0.7987 - val_loss: 0.4959 - val_accuracy: 0.7927


In [195]:
#Make predictions
model_6_pred_probs=model_6.predict(val_sentences)
model_6_pred_probs

24/24 [==============================] - 1s 19ms/step


array([[0.35161564],
       [0.6891301 ],
       [0.8524273 ],
       [0.35444233],
       [0.64164054],
       [0.72213525],
       [0.82817763],
       [0.83883035],
       [0.74394643],
       [0.19880618],
       [0.54153204],
       [0.48303577],
       [0.42178598],
       [0.46238017],
       [0.4959602 ],
       [0.17271355],
       [0.3453706 ],
       [0.49210456],
       [0.5195231 ],
       [0.5022646 ],
       [0.63838494],
       [0.29874006],
       [0.4601072 ],
       [0.16130714],
       [0.6137609 ],
       [0.79713607],
       [0.24751458],
       [0.30635315],
       [0.24569707],
       [0.34957093],
       [0.54838145],
       [0.7574002 ],
       [0.45782018],
       [0.48496887],
       [0.5105053 ],
       [0.2019349 ],
       [0.78702515],
       [0.16655482],
       [0.18981917],
       [0.80969155],
       [0.2343275 ],
       [0.30271477],
       [0.5536191 ],
       [0.56575245],
       [0.27554742],
       [0.73854256],
       [0.31260368],
       [0.843

In [196]:
model_6_preds=tf.squeeze(tf.round(model_6_pred_probs))
model_6_preds

<tf.Tensor: shape=(762,), dtype=float32, numpy=
array([0., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 1., 1., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0.,
       1., 0., 1., 0., 0., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0.,
       1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0.,
       0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 0.,
       1., 0., 0., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 0.,
       0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 1.,
       1., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 0.,
       1., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 1.,
       0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       1., 1., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 1., 1., 1., 0., 0.,
       1., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 1., 0., 1., 1., 1., 0., 1., 0., 0., 0., 0

In [197]:
model_6_results=calculate_results(y_true=val_labels,
                  y_pred=model_6_preds)

In [198]:
model_6_results

{'accuracy': 79.26509186351706,
 'precision': 0.7930624875358199,
 'recall': 0.7926509186351706,
 'f1-score': 0.7916058782200516}

In [1]:
baseline_results

NameError: ignored